//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testPruebaEntities : DbContext
    {
        public testPruebaEntities()
            : base("name=testPruebaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Empleados> Empleados { get; set; }
        public DbSet<EmpleadosEntidad> EmpleadosEntidad { get; set; }
        public DbSet<Entidades> Entidades { get; set; }
        public DbSet<TipoIdentificacion> TipoIdentificacion { get; set; }
    }
}
