//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoIdentificacion
    {
        public TipoIdentificacion()
        {
            this.Empleados = new HashSet<Empleados>();
        }
    
        public int id { get; set; }
        public string acronimo { get; set; }
        public string titulo { get; set; }
    
        public virtual ICollection<Empleados> Empleados { get; set; }
    }
}
